# Generated by Django 5.2.17 on 2026-08-22 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_placeimage_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('title', 'lat', 'lng')},
        ),
    ]
