# Generated by Django 5.2.17 on 2026-08-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_rename_description_long_place_long_description_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='placeimage',
            index=models.Index(fields=['position'], name='places_plac_positio_6c754e_idx'),
        ),
    ]
